services:

  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports: 
      - "3000:3000"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: